[package]
name = "util"
version.workspace = true
edition.workspace = true

[dependencies]
ahash.workspace = true
dashmap.workspace = true
glam.workspace = true
serde.workspace = true
thiserror.workspace = true

[features]
exhaustive_enums = []
