[package]
name = "interpreter"
version.workspace = true
edition.workspace = true

[dependencies]
datapack = { path = "../datapack", features = ["exhaustive_enums"] }
ahash.workspace = true
ordered-float.workspace = true
thiserror.workspace = true
